- name: Demo on Loops
  hosts: all
  tasks:  
    - name: Printing a Loop
      ansible.builtin.debug:
        msg: Value in the loop is {{item}}
      loop:
        - 10
        - 20
        - 30
        - 40
        - 50
