- name: Installing Maven
  ansible.builtin.yum:
    name: maven
    state: present

- name: Creating the user {{APPUSER}}
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: roboshop service user

- name: Download and extracting
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{component}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Cleaning the OLD content
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{component}}/
    state: absent

- name: Copying files to roboshop home directory
  ansible.builtin.copy:
    src: /tmp/{{component}}-main/
    dest: /home/{{APPUSER}}/{{component}}/
    remote_src: yes
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"

- name: Preparing maven artifacts
  ansible.builtin.shell: mvn clean package && mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /home/{{APPUSER}}/{{component}}

- name: Configuring the systemd service file
  ansible.builtin.template:
    src: shipping.service
    dest: /etc/systemd/system/{{component}}.service

- name: Restarting service
  ansible.builtin.service:
    name: shipping
    state: started
    daemon-reload: yes