- name: Demo on conditions
  hosts: all
  tasks:
    - name: Run this on centos machione only
      ansible.builtin.debug:
        msg: Hai I am on centos
      when: ansible_distribution = "CentOS"

    - name: Run this on Ubuntu machine only
      ansible.builtin.debug:
        msg: Hai I am on Ubuntu
      when: ansible_distribution = "Ubuntu"