- name: Demo on Ignore facts
  hosts: all
  tasks:
    - name: Checking where tomcat is running or not
      ansible.builtin.shell:
      register: OUT
      ignore_errors: yes

    - name: Starting tomcat
      ansible.builtin.debug:
        msg: Starting tomcat