- name: Demo on shell
  hosts: all
  tasks:
    - name: task1 - Execute shell command
      ansible.builtin.shell: uptime
      register: OUT

    - name: task2 -Printing OUT variable
      ansible.builtin.debug:
        msg: "{{OUT.stdout}}"