- name: Demo on shell
  hosts: all
  tasks:
    - name: task1 - Execute shell command
      ansible.builtin.shell: uptime
      register: OUT

    - name: task2 -Printing OUT variable
      ansible.builtin.debug:
        msg: "{{OUT.stdout}}"

    - name: task3 - Declaring the variable
      ansible.builtin.set_fact:
        STATUS: "{{OUT.rc}}"

    - name: task4 - -Printing Exit code
      ansible.builtin.debug:
        msg: "{{STATUS}}"