- name: Installing python modules
  ansible.builtin.yum:
    name: "{{item}}"
    state: present
  loop:
    - python3
    - gcc
    - pip3
    - python3-devel

- name: Creating the user {{APPUSER}}
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: roboshop service user

- name: Download and extracting
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{component}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Cleaning the OLD content
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{component}}/
    state: absent

- name: Copying files to roboshop home directory
  ansible.builtin.copy:
    src: /tmp/{{component}}-main/
    dest: /home/{{APPUSER}}/{{component}}/
    remote_src: yes
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
  register: APPUSER_INFO

- name: Install specified python requirements
  ansible.builtin.pip:
    requirements: /home/{{APPUSER}}/{{component}}/requirments.txt
    executable: pip3

- name: Test Printout
  ansible.builtin.debug:
    msg: "{{APPUSER_INFO}}"