- name: Downloading RabbitMQ dependencies
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: Downloading YUM Repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install NodeJS
  ansible.builtin.package:
    name: rabbitmq-server
    state: present

- name: Restarting service
  ansible.builtin.service:
    name: rabbitmq-server
    enabled: yes
    state: started