- name: deploy mysql repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install mySQL
  ansible.builtin.package:
    name: 
      - mysql-community-server
      - MySQL-python
    state: present

- name: Start service mySQL, if not started
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Checking Default Root Password
  block:
    - name: Fetch MySQL version to check the DB Connection
      mysql_info:
        login_user: root
        login_password: "{{DB_PASSWORD}}"
        filter: version
  rescue:
    - name: Load MYSQL Log File
      ansible.builtin.slurp:
        src: /var/log/mysqld.log
      register: mysql_log

    - name: Declare Facts
      ansible.builtin.set_fact:
        DEFAULT_PASS: "{{mysql_log['content'] | b64decode | regex_findall('.*temporary password.*') | join(' ') |split(' ') | last }}"

    - name: Change MySQL
      ansible.builtin.shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{DB_PASSWORD}}';" | mysql --connect-expired-password -uroot -p"{{DEFAULT_PASS}}"

- name: Check Validate plugin exists
  ansible.builtin.shell: echo "uninstall plugin validate_password;" | mysql -uroot -p{{DB_PASSWORD}}
  ignore_errors: yes

- name: Download and extracting the Component 
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp 
    remote_src: yes  

- name: Cleanup of Old Content 
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/ 
    state: absent  
  ignore_errors: yes

- name: Copy files to the roboshop home directory
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    remote_src: yes
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}" 
  ignore_errors: yes 

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /tmp/mysql-main/shipping.sql
    login_user: root
    login_password: "{{DB_PASSWORD}}"