- name: Configuring NodeJS Repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install NodeJS
  ansible.builtin.package:
    name: nodejs
    state: present