- name: Configuring NodeJS Repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install NodeJS
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Creating the user {{APPUSER}}
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: roboshop service user

